"""Add _is_admin property to users

Revision ID: 2a9b4c9380f
Revises: e76a8b393b
Create Date: 2015-12-17 16:56:40.186024

"""

# revision identifiers, used by Alembic.
revision = '2a9b4c9380f'
down_revision = 'e76a8b393b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.add_column('users', sa.Column('_is_admin', sa.Boolean(), nullable=False,
                                     server_default=sa.sql.expression.false()))


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_is_admin')
    ### end Alembic commands ###
