"""Remove not null cndition on user phone number

Revision ID: 44b8fe48396
Revises: 2a9b4c9380f
Create Date: 2015-12-17 17:31:06.228449

"""

# revision identifiers, used by Alembic.
revision = '44b8fe48396'
down_revision = '2a9b4c9380f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    ### end Alembic commands ###
