"""add default admin user

Revision ID: 9b646c49f3
Revises: 44b8fe48396
Create Date: 2015-12-17 17:40:51.424647

"""

# revision identifiers, used by Alembic.
revision = '9b646c49f3'
down_revision = '44b8fe48396'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import os
import hashlib


def upgrade():
    HASH_SIZE = 32

    users = sa.table('users', sa.Column('id'),
                     sa.Column('full_name', sa.String),
                     sa.Column('email', sa.String),
                     sa.Column('_salt', sa.Binary(HASH_SIZE)),
                     sa.Column('_hashed_password', sa.Binary(HASH_SIZE)),
                     sa.Column('_active', sa.Boolean),
                     sa.Column('_is_admin', sa.Boolean),
                     )

    default_password = 'Autoconstruccion'
    salt = os.urandom(HASH_SIZE)
    pwd = hashlib.sha256(salt + bytes(default_password, encoding='utf8')).digest()

    op.bulk_insert(users, [
        {'full_name': 'Administrator',
         'email': 'admin@autoconstruccion.org',
         '_salt': salt,
         '_hashed_password': pwd,
         '_active': True,
         '_is_admin': True
         }
    ])

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
